
import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Advanced blockchain hash generation with zk-SNARK simulation
async function generateZkProof(data: any): Promise<{hash: string, zkProof: string}> {
  // In a real implementation, this would use a zk-SNARK library
  // For this example, we're simulating the process
  
  // Create a deterministic hash
  const encoder = new TextEncoder();
  const dataString = JSON.stringify({
    ...data,
    timestamp: new Date().toISOString()
  });
  
  // Use crypto.subtle for primary hash
  const dataBuffer = encoder.encode(dataString);
  const hashBuffer = await crypto.subtle.digest('SHA-256', dataBuffer);
  
  // Convert to hex string
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  
  // Simulate a zk-proof (would be generated by a proper zk-SNARK library in production)
  const zkProofBase = await crypto.subtle.digest('SHA-512', dataBuffer);
  const zkProofArray = Array.from(new Uint8Array(zkProofBase));
  const zkProof = zkProofArray.map(b => b.toString(16).padStart(2, '0')).join('').substring(0, 128);
  
  return {
    hash: `0x${hashHex}`,
    zkProof: `zk_${zkProof}`
  };
}

// Simulate storing data on Hyperledger Fabric with advanced features
async function simulateHyperledgerTransaction(
  hash: string, 
  zkProof: string, 
  data: any
): Promise<any> {
  // Simulate transaction processing time
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  // Generate a Fabric-like transaction ID
  const txId = Array.from({length: 64}, () => 
    Math.floor(Math.random() * 16).toString(16)
  ).join('');
  
  // Simulate a block number
  const blockNumber = Math.floor(Math.random() * 1000000) + 9000000;
  
  // Create temporal verification data
  const timestamp = new Date().toISOString();
  const validUntil = new Date();
  validUntil.setFullYear(validUntil.getFullYear() + 1); // Valid for 1 year
  
  return {
    success: true,
    transactionId: txId,
    blockNumber,
    hash,
    zkProof,
    timestamp,
    validUntil: validUntil.toISOString(),
    network: "ProcureChain Hyperledger Fabric",
    verificationNodes: ["node1.procurechain.gov", "node2.procurechain.gov", "node3.procurechain.gov"],
    consensusType: "PBFT",
    endorsementPolicy: "Majority",
  };
}

// Behavioral analysis to enhance verification security
function analyzeVerificationBehavior(
  userId: string, 
  verificationType: string, 
  submissionMetadata: any
): number {
  // This function would include sophisticated AI-based analysis in production
  // For now, we'll use a simple heuristic approach
  
  let riskScore = 0;
  
  // Time-based analysis (unusual submission times may indicate automation/bots)
  const hour = new Date().getHours();
  if (hour < 6 || hour > 22) {
    riskScore += 10; // Unusual business hours
  }
  
  // Submission frequency analysis
  if (submissionMetadata.recent_submissions > 5) {
    riskScore += 15; // Unusual number of submissions in a short time
  }
  
  // IP address analysis (would be more sophisticated in production)
  if (submissionMetadata.ip_address && submissionMetadata.ip_country !== "Kenya") {
    riskScore += 20; // Non-local IP for local business verification
  }
  
  // Device fingerprint analysis
  if (submissionMetadata.device_changed) {
    riskScore += 15; // Recently changed device
  }
  
  return Math.min(riskScore, 100); // Cap at 100
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }
  
  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    );
    
    // Get the current user
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser();
    
    if (userError || !user) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 401 }
      );
    }
    
    // Get request body
    const { 
      verificationType, 
      verificationData, 
      businessId,
      submissionMetadata = {}
    } = await req.json();
    
    if (!verificationType || !businessId) {
      return new Response(
        JSON.stringify({ error: 'Verification type and business ID are required' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      );
    }
    
    console.log(`Processing ${verificationType} verification for business ID ${businessId}`);
    
    // Generate zk-proof and blockchain hash
    const dataToHash = {
      user_id: user.id,
      business_id: businessId,
      verification_type: verificationType,
      verification_data: verificationData || {},
    };
    
    const { hash, zkProof } = await generateZkProof(dataToHash);
    console.log(`Generated hash: ${hash}`);
    console.log(`Generated zk-proof: ${zkProof}`);
    
    // Analyze submission behavior
    const riskScore = analyzeVerificationBehavior(user.id, verificationType, submissionMetadata);
    console.log(`Risk score: ${riskScore}`);
    
    // Store hash on blockchain (simulated)
    const blockchainResponse = await simulateHyperledgerTransaction(hash, zkProof, dataToHash);
    console.log(`Blockchain transaction: ${blockchainResponse.transactionId}`);
    
    // Determine verification status based on risk score
    const initialStatus = riskScore > 50 
      ? 'flagged' 
      : (riskScore > 30 ? 'in_progress' : 'in_progress');
    
    // Store verification record in database
    const { data: verificationRecord, error: insertError } = await supabaseClient
      .from('digital_identity_verification')
      .insert({
        user_id: user.id,
        business_id: businessId,
        verification_type: verificationType,
        verification_status: initialStatus,
        verification_data: {
          ...verificationData || {},
          risk_score: riskScore,
          zkProof: zkProof,
          submission_metadata: submissionMetadata
        },
        blockchain_hash: hash
      })
      .select()
      .single();
    
    if (insertError) {
      console.error('Error inserting verification record:', insertError);
      return new Response(
        JSON.stringify({ error: 'Failed to store verification record' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      );
    }
    
    // Record blockchain transaction
    await supabaseClient
      .from('blockchain_transactions')
      .insert({
        entity_id: verificationRecord.id,
        hash: hash,
        transaction_type: 'identity_verification',
        status: 'confirmed',
        metadata: {
          blockchain_response: blockchainResponse,
          verification_type: verificationType,
          risk_score: riskScore,
          zk_proof: zkProof
        }
      });
    
    // Insert behavior analysis record
    await supabaseClient
      .from('behavior_analysis')
      .insert({
        entity_id: user.id,
        entity_type: 'user',
        analysis_type: 'identity_verification_behavior',
        risk_score: riskScore,
        analysis_data: {
          verification_id: verificationRecord.id,
          timestamp: new Date().toISOString(),
          submission_metadata: submissionMetadata,
          factors: {
            time_of_day: new Date().getHours(),
            day_of_week: new Date().getDay(),
            submission_pattern: submissionMetadata.recent_submissions || 0
          }
        }
      });
    
    // Update profile verification status
    await supabaseClient
      .from('profiles')
      .update({ 
        verification_status: initialStatus,
        risk_score: riskScore
      })
      .eq('id', user.id);
    
    return new Response(
      JSON.stringify({
        success: true,
        verification_id: verificationRecord.id,
        blockchain_hash: hash,
        zk_proof: zkProof,
        risk_score: riskScore,
        blockchain_transaction: blockchainResponse
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
    
  } catch (error) {
    console.error('Error processing blockchain verification:', error);
    
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
