import { EvaluationCriteriaCategory } from '@/types/enums';

export interface CriteriaGroup {
  name: string;
  key: string;
  criteria: Array<{ value: EvaluationCriteriaCategory; label: string }>;
}

export const criteriaGroups: CriteriaGroup[] = [
  {
    name: 'Financial',
    key: 'financial',
    criteria: [
      { value: EvaluationCriteriaCategory.PRICE_COMPETITIVENESS, label: 'Price Competitiveness' },
      { value: EvaluationCriteriaCategory.FINANCIAL_STABILITY, label: 'Financial Stability' },
      { value: EvaluationCriteriaCategory.COST_EFFECTIVENESS, label: 'Cost Effectiveness' },
      { value: EvaluationCriteriaCategory.LIFECYCLE_COSTS, label: 'Lifecycle Costs' },
      { value: EvaluationCriteriaCategory.PAYMENT_TERMS, label: 'Payment Terms' },
      { value: EvaluationCriteriaCategory.BUDGET_ADHERENCE, label: 'Budget Adherence' },
      { value: EvaluationCriteriaCategory.PRICING_STRUCTURE_TRANSPARENCY, label: 'Pricing Structure Transparency' },
      { value: EvaluationCriteriaCategory.INFLATION_ADJUSTMENT_MECHANISM, label: 'Inflation Adjustment Mechanism' },
      { value: EvaluationCriteriaCategory.CREDIT_TERMS, label: 'Credit Terms' },
      { value: EvaluationCriteriaCategory.FINANCIAL_REPORTING_ACCURACY, label: 'Financial Reporting Accuracy' },
      { value: EvaluationCriteriaCategory.PROFIT_MARGIN, label: 'Profit Margin' },
      { value: EvaluationCriteriaCategory.TAX_COMPLIANCE, label: 'Tax Compliance' },
      { value: EvaluationCriteriaCategory.TOTAL_COST_OF_OWNERSHIP, label: 'Total Cost of Ownership' },
      { value: EvaluationCriteriaCategory.DISCOUNT_INCENTIVE_TERMS, label: 'Discount & Incentive Terms' },
      { value: EvaluationCriteriaCategory.CURRENCY_RISK_MANAGEMENT, label: 'Currency Risk Management' },
      { value: EvaluationCriteriaCategory.FINANCIAL_HEALTH_INDICATORS, label: 'Financial Health Indicators' },
      { value: EvaluationCriteriaCategory.CREDITWORTHINESS, label: 'Creditworthiness' },
      { value: EvaluationCriteriaCategory.CASH_FLOW_STABILITY, label: 'Cash Flow Stability' },
      { value: EvaluationCriteriaCategory.BONDING_CAPACITY, label: 'Bonding Capacity' },
      { value: EvaluationCriteriaCategory.WARRANTY_GUARANTEE_TERMS, label: 'Warranty & Guarantee Terms' },
      { value: EvaluationCriteriaCategory.COST_ESCALATION_POLICIES, label: 'Cost Escalation Policies' },
      { value: EvaluationCriteriaCategory.PRICE_ADJUSTMENT_FLEXIBILITY, label: 'Price Adjustment Flexibility' },
      { value: EvaluationCriteriaCategory.FINANCING_AVAILABILITY, label: 'Financing Availability' },
      { value: EvaluationCriteriaCategory.INVOICE_ACCURACY, label: 'Invoice Accuracy' },
      { value: EvaluationCriteriaCategory.AUDIT_REPORTING_TRANSPARENCY, label: 'Audit & Reporting Transparency' },
      { value: EvaluationCriteriaCategory.CONTRACTUAL_PENALTY_TERMS, label: 'Contractual Penalty Terms' },
      { value: EvaluationCriteriaCategory.VALUE_FOR_MONEY_ANALYSIS, label: 'Value for Money Analysis' },
    ],
  },
  {
    name: 'Technical',
    key: 'technical',
    criteria: [
      { value: EvaluationCriteriaCategory.TECHNICAL_CAPABILITY, label: 'Technical Capability' },
      { value: EvaluationCriteriaCategory.METHODOLOGY, label: 'Methodology' },
      { value: EvaluationCriteriaCategory.INNOVATION, label: 'Innovation' },
      { value: EvaluationCriteriaCategory.QUALITY_STANDARDS, label: 'Quality Standards' },
      { value: EvaluationCriteriaCategory.TECHNICAL_COMPLIANCE, label: 'Technical Compliance' },
      { value: EvaluationCriteriaCategory.TECHNICAL_DOCUMENTATION_QUALITY, label: 'Technical Documentation Quality' },
      { value: EvaluationCriteriaCategory.SYSTEM_INTEGRATION_CAPABILITY, label: 'System Integration Capability' },
      { value: EvaluationCriteriaCategory.PROTOTYPING_TESTING_APPROACH, label: 'Prototyping & Testing Approach' },
      { value: EvaluationCriteriaCategory.SCALABILITY, label: 'Scalability' },
      { value: EvaluationCriteriaCategory.MAINTENANCE_SUPPORT, label: 'Maintenance Support' },
      { value: EvaluationCriteriaCategory.TECHNOLOGY_MATURITY, label: 'Technology Maturity' },
      { value: EvaluationCriteriaCategory.COMPLIANCE_WITH_TECHNICAL_STANDARDS, label: 'Compliance with Technical Standards' },
      { value: EvaluationCriteriaCategory.PRODUCT_RELIABILITY, label: 'Product Reliability' },
      { value: EvaluationCriteriaCategory.PRODUCT_PERFORMANCE, label: 'Product Performance' },
      { value: EvaluationCriteriaCategory.DESIGN_FUNCTIONALITY, label: 'Design & Functionality' },
      { value: EvaluationCriteriaCategory.TECHNICAL_SUPPORT_HELPDESK, label: 'Technical Support & Helpdesk' },
      { value: EvaluationCriteriaCategory.TECHNOLOGY_ROADMAP, label: 'Technology Roadmap' },
      { value: EvaluationCriteriaCategory.SOFTWARE_COMPATIBILITY, label: 'Software Compatibility' },
      { value: EvaluationCriteriaCategory.PRODUCT_CERTIFICATION, label: 'Product Certification' },
      { value: EvaluationCriteriaCategory.USABILITY_USER_EXPERIENCE, label: 'Usability & User Experience' },
      { value: EvaluationCriteriaCategory.CUSTOMIZATION_FLEXIBILITY, label: 'Customization Flexibility' },
      { value: EvaluationCriteriaCategory.TRAINING_PROVISION, label: 'Training Provision' },
      { value: EvaluationCriteriaCategory.TECHNICAL_WARRANTY_TERMS, label: 'Warranty Terms' },
      { value: EvaluationCriteriaCategory.RESEARCH_DEVELOPMENT_FOCUS, label: 'Research & Development Focus' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_COMPLIANCE_TECHNICAL, label: 'Environmental Compliance of Technical Solutions' },
      { value: EvaluationCriteriaCategory.DATA_SECURITY_CONTROLS, label: 'Data Security Controls' },
      { value: EvaluationCriteriaCategory.PRODUCT_SAFETY_STANDARDS, label: 'Product Safety Standards' },
    ],
  },
  {
    name: 'Experience',
    key: 'experience',
    criteria: [
      { value: EvaluationCriteriaCategory.RELEVANT_EXPERIENCE, label: 'Relevant Experience' },
      { value: EvaluationCriteriaCategory.PAST_PERFORMANCE, label: 'Past Performance' },
      { value: EvaluationCriteriaCategory.QUALIFICATIONS, label: 'Qualifications' },
      { value: EvaluationCriteriaCategory.INDUSTRY_EXPERTISE, label: 'Industry Expertise' },
      { value: EvaluationCriteriaCategory.KEY_PERSONNEL, label: 'Key Personnel' },
      { value: EvaluationCriteriaCategory.PROJECT_MANAGEMENT, label: 'Project Management' },
      { value: EvaluationCriteriaCategory.CLIENT_REFERENCES, label: 'Client References' },
      { value: EvaluationCriteriaCategory.CONTRACT_DISPUTE_HISTORY, label: 'Contract Dispute History' },
      { value: EvaluationCriteriaCategory.INDUSTRY_AWARDS_RECOGNITIONS, label: 'Industry Awards & Recognitions' },
      { value: EvaluationCriteriaCategory.REPEAT_BUSINESS_RATE, label: 'Repeat Business Rate' },
      { value: EvaluationCriteriaCategory.TRAINING_DEVELOPMENT_PROGRAMS, label: 'Training & Development Programs' },
      { value: EvaluationCriteriaCategory.SUBCONTRACTOR_MANAGEMENT, label: 'Subcontractor Management' },
      { value: EvaluationCriteriaCategory.RELEVANT_CERTIFICATIONS, label: 'Relevant Certifications' },
      { value: EvaluationCriteriaCategory.CROSS_INDUSTRY_EXPERIENCE, label: 'Cross-Industry Experience' },
      { value: EvaluationCriteriaCategory.SUPPLIER_STABILITY_LONGEVITY, label: 'Supplier Stability & Longevity' },
      { value: EvaluationCriteriaCategory.MARKET_REPUTATION, label: 'Market Reputation' },
      { value: EvaluationCriteriaCategory.TRACK_RECORD_ON_TIME_DELIVERY, label: 'Track Record of On-Time Delivery' },
      { value: EvaluationCriteriaCategory.INNOVATION_EXPERIENCE, label: 'Innovation Experience' },
      { value: EvaluationCriteriaCategory.CRISIS_MANAGEMENT_EXPERIENCE, label: 'Crisis Management Experience' },
      { value: EvaluationCriteriaCategory.RELATIONSHIP_MANAGEMENT, label: 'Relationship Management' },
      { value: EvaluationCriteriaCategory.SCALABILITY_EXPERIENCE, label: 'Scalability Experience' },
    ],
  },
  {
    name: 'Operational',
    key: 'operational',
    criteria: [
      { value: EvaluationCriteriaCategory.DELIVERY_TIMEFRAME, label: 'Delivery Timeframe' },
      { value: EvaluationCriteriaCategory.IMPLEMENTATION_PLAN, label: 'Implementation Plan' },
      { value: EvaluationCriteriaCategory.OPERATIONAL_CAPACITY, label: 'Operational Capacity' },
      { value: EvaluationCriteriaCategory.QUALITY_ASSURANCE, label: 'Quality Assurance' },
      { value: EvaluationCriteriaCategory.SERVICE_LEVEL_AGREEMENTS, label: 'Service Level Agreements' },
      { value: EvaluationCriteriaCategory.RESOURCE_AVAILABILITY, label: 'Resource Availability' },
      { value: EvaluationCriteriaCategory.SUPPLY_CHAIN_ROBUSTNESS, label: 'Supply Chain Robustness' },
      { value: EvaluationCriteriaCategory.CONTINGENCY_PLANNING, label: 'Contingency Planning' },
      { value: EvaluationCriteriaCategory.AFTER_SALES_SERVICE, label: 'After-Sales Service' },
      { value: EvaluationCriteriaCategory.CUSTOMER_SUPPORT_RESPONSIVENESS, label: 'Customer Support Responsiveness' },
      { value: EvaluationCriteriaCategory.TRAINING_KNOWLEDGE_TRANSFER, label: 'Training & Knowledge Transfer' },
      { value: EvaluationCriteriaCategory.DISASTER_RECOVERY_PLAN, label: 'Disaster Recovery Plan' },
      { value: EvaluationCriteriaCategory.INVENTORY_MANAGEMENT, label: 'Inventory Management' },
      { value: EvaluationCriteriaCategory.LOGISTICS_TRANSPORTATION_CAPABILITY, label: 'Logistics & Transportation Capability' },
      { value: EvaluationCriteriaCategory.TECHNOLOGY_INFRASTRUCTURE, label: 'Technology Infrastructure' },
      { value: EvaluationCriteriaCategory.WORKSITE_SAFETY_PROTOCOLS, label: 'Worksite Safety Protocols' },
      { value: EvaluationCriteriaCategory.COMMUNICATION_TRANSPARENCY, label: 'Communication Transparency' },
      { value: EvaluationCriteriaCategory.FLEXIBILITY_ADAPTABILITY, label: 'Flexibility & Adaptability' },
      { value: EvaluationCriteriaCategory.CAPACITY_TO_SCALE, label: 'Capacity to Scale' },
      { value: EvaluationCriteriaCategory.BUSINESS_CONTINUITY_PLANNING, label: 'Business Continuity Planning' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_MANAGEMENT_SYSTEMS, label: 'Environmental Management Systems' },
    ],
  },
  {
    name: 'Compliance',
    key: 'compliance',
    criteria: [
      { value: EvaluationCriteriaCategory.LEGAL_COMPLIANCE, label: 'Legal Compliance' },
      { value: EvaluationCriteriaCategory.REGULATORY_COMPLIANCE, label: 'Regulatory Compliance' },
      { value: EvaluationCriteriaCategory.RISK_MANAGEMENT, label: 'Risk Management' },
      { value: EvaluationCriteriaCategory.INSURANCE_COVERAGE, label: 'Insurance Coverage' },
      { value: EvaluationCriteriaCategory.SECURITY_MEASURES, label: 'Security Measures' },
      { value: EvaluationCriteriaCategory.DATA_PRIVACY_COMPLIANCE, label: 'Data Privacy Compliance' },
      { value: EvaluationCriteriaCategory.ETHICAL_SOURCING, label: 'Ethical Sourcing' },
      { value: EvaluationCriteriaCategory.ANTI_CORRUPTION_MEASURES, label: 'Anti-corruption Measures' },
      { value: EvaluationCriteriaCategory.HEALTH_SAFETY_RECORD, label: 'Health & Safety Record' },
      { value: EvaluationCriteriaCategory.LABOR_STANDARDS_COMPLIANCE, label: 'Labor Standards Compliance' },
      { value: EvaluationCriteriaCategory.INTELLECTUAL_PROPERTY_RIGHTS_COMPLIANCE, label: 'Intellectual Property Rights Compliance' },
      { value: EvaluationCriteriaCategory.TRANSPARENCY_DISCLOSURE, label: 'Transparency & Disclosure' },
      { value: EvaluationCriteriaCategory.AUDIT_INSPECTION_READINESS, label: 'Audit & Inspection Readiness' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_REGULATIONS_COMPLIANCE, label: 'Environmental Regulations Compliance' },
      { value: EvaluationCriteriaCategory.TRADE_COMPLIANCE, label: 'Trade Compliance' },
      { value: EvaluationCriteriaCategory.EXPORT_IMPORT_CONTROLS, label: 'Export/Import Controls' },
      { value: EvaluationCriteriaCategory.CONFLICT_OF_INTEREST_POLICIES, label: 'Conflict of Interest Policies' },
      { value: EvaluationCriteriaCategory.PUBLIC_PROCUREMENT_RULES_ADHERENCE, label: 'Public Procurement Rules Adherence' },
      { value: EvaluationCriteriaCategory.SOCIAL_RESPONSIBILITY_COMPLIANCE, label: 'Social Responsibility Compliance' },
      { value: EvaluationCriteriaCategory.ANTI_BRIBERY_POLICIES, label: 'Anti-Bribery Policies' },
      { value: EvaluationCriteriaCategory.WHISTLEBLOWER_PROTECTIONS, label: 'Whistleblower Protections' },
      { value: EvaluationCriteriaCategory.COMPLIANCE_TRAINING_PROGRAMS, label: 'Compliance Training Programs' },
      { value: EvaluationCriteriaCategory.DISASTER_EMERGENCY_COMPLIANCE, label: 'Disaster & Emergency Compliance' },
    ],
  },
  {
    name: 'Sustainability',
    key: 'sustainability',
    criteria: [
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_SUSTAINABILITY, label: 'Environmental Sustainability' },
      { value: EvaluationCriteriaCategory.SOCIAL_RESPONSIBILITY, label: 'Social Responsibility' },
      { value: EvaluationCriteriaCategory.LOCAL_CONTENT, label: 'Local Content' },
      { value: EvaluationCriteriaCategory.DIVERSITY_INCLUSION, label: 'Diversity & Inclusion' },
      { value: EvaluationCriteriaCategory.COMMUNITY_IMPACT, label: 'Community Impact' },
      { value: EvaluationCriteriaCategory.CARBON_FOOTPRINT_REDUCTION, label: 'Carbon Footprint Reduction Plan' },
      { value: EvaluationCriteriaCategory.WASTE_MANAGEMENT_STRATEGY, label: 'Waste Management Strategy' },
      { value: EvaluationCriteriaCategory.ENERGY_EFFICIENCY, label: 'Energy Efficiency' },
      { value: EvaluationCriteriaCategory.WATER_USAGE_MANAGEMENT, label: 'Water Usage Management' },
      { value: EvaluationCriteriaCategory.CIRCULAR_ECONOMY_PRACTICES, label: 'Circular Economy Practices' },
      { value: EvaluationCriteriaCategory.SUSTAINABLE_PROCUREMENT_POLICIES, label: 'Sustainable Procurement Policies' },
      { value: EvaluationCriteriaCategory.SOCIAL_EQUITY_CONTRIBUTION, label: 'Social Equity Contribution' },
      { value: EvaluationCriteriaCategory.CLIMATE_RISK_MANAGEMENT, label: 'Climate Risk Management' },
      { value: EvaluationCriteriaCategory.SUSTAINABILITY_CERTIFICATIONS, label: 'Sustainability Certifications' },
      { value: EvaluationCriteriaCategory.RENEWABLE_ENERGY_USAGE, label: 'Renewable Energy Usage' },
      { value: EvaluationCriteriaCategory.EMISSIONS_MONITORING, label: 'Emissions Monitoring' },
      { value: EvaluationCriteriaCategory.RESOURCE_CONSERVATION_MEASURES, label: 'Resource Conservation Measures' },
      { value: EvaluationCriteriaCategory.STAKEHOLDER_ENGAGEMENT, label: 'Stakeholder Engagement' },
      { value: EvaluationCriteriaCategory.LABOR_RIGHTS_FAIR_TRADE, label: 'Labor Rights & Fair Trade' },
      { value: EvaluationCriteriaCategory.SUPPLIER_DIVERSITY_PROGRAMS, label: 'Supplier Diversity Programs' },
      { value: EvaluationCriteriaCategory.GREEN_PRODUCT_INNOVATION, label: 'Green Product Innovation' },
      { value: EvaluationCriteriaCategory.ECOLOGICAL_IMPACT_ASSESSMENT, label: 'Ecological Impact Assessment' },
      { value: EvaluationCriteriaCategory.LONG_TERM_SUSTAINABILITY_GOALS, label: 'Long-term Sustainability Goals' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_REPORTING_AUDIT, label: 'Environmental Reporting & Audit' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_RISK_MITIGATION, label: 'Environmental Risk Mitigation' },
      { value: EvaluationCriteriaCategory.CLIMATE_ADAPTATION_PLANNING, label: 'Climate Adaptation Planning' },
    ],
  },
  {
    name: 'Risk Mitigation',
    key: 'risk_mitigation',
    criteria: [
      { value: EvaluationCriteriaCategory.RISK_IDENTIFICATION_ASSESSMENT, label: 'Risk Identification and Assessment' },
      { value: EvaluationCriteriaCategory.RISK_RESPONSE_PLANNING, label: 'Risk Response Planning' },
      { value: EvaluationCriteriaCategory.FINANCIAL_RISK_CONTROLS, label: 'Financial Risk Controls' },
      { value: EvaluationCriteriaCategory.SUPPLY_CHAIN_RISK_MANAGEMENT, label: 'Supply Chain Risk Management' },
      { value: EvaluationCriteriaCategory.MARKET_RISK_ANALYSIS, label: 'Market Risk Analysis' },
      { value: EvaluationCriteriaCategory.TECHNICAL_RISK_MITIGATION, label: 'Technical Risk Mitigation' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_RISK_MANAGEMENT_PLAN, label: 'Environmental Risk Management' },
      { value: EvaluationCriteriaCategory.SOCIAL_RISK_MANAGEMENT, label: 'Social Risk Management' },
    ],
  },
  {
    name: 'Preliminary/Mandatory Checks',
    key: 'preliminary_mandatory',
    criteria: [
      { value: EvaluationCriteriaCategory.BID_COMPLETENESS_DOCUMENTATION, label: 'Bid Completeness and Documentation' },
      { value: EvaluationCriteriaCategory.MANDATORY_QUALIFICATION_COMPLIANCE, label: 'Mandatory Qualification Compliance' },
      { value: EvaluationCriteriaCategory.BIDDER_REGISTRATION_VALIDATION, label: 'Bidder Registration Validation' },
      { value: EvaluationCriteriaCategory.PROOF_OF_LICENSES_PERMITS, label: 'Proof of Licenses and Permits' },
      { value: EvaluationCriteriaCategory.EVIDENCE_OF_TAX_COMPLIANCE, label: 'Evidence of Tax Compliance' },
      { value: EvaluationCriteriaCategory.SUBMISSION_TIMELINESS, label: 'Submission Timeliness' },
      { value: EvaluationCriteriaCategory.ADHERENCE_TO_BID_FORMAT, label: 'Adherence to Bid Format Requirements' },
    ],
  },
  {
    name: 'Health, Safety, Environment & Community',
    key: 'hsec',
    criteria: [
      { value: EvaluationCriteriaCategory.SITE_ACCESS_CONDITIONS_COMPLIANCE, label: 'Site Access Conditions Compliance' },
      { value: EvaluationCriteriaCategory.HEALTH_SAFETY_POLICIES_RECORDS, label: 'Health and Safety Policies and Records' },
      { value: EvaluationCriteriaCategory.ENVIRONMENTAL_MANAGEMENT_PLANS, label: 'Environmental Management Plans' },
      { value: EvaluationCriteriaCategory.COMMUNITY_ENGAGEMENT_APPROACHES, label: 'Community Engagement Approaches' },
      { value: EvaluationCriteriaCategory.IMPACT_MITIGATION_PLANS, label: 'Impact Mitigation Plans' },
      { value: EvaluationCriteriaCategory.EMERGENCY_RESPONSE_PLANS, label: 'Emergency Response Plans' },
      { value: EvaluationCriteriaCategory.OCCUPATIONAL_HEALTH_TRAINING, label: 'Occupational Health Training' },
      { value: EvaluationCriteriaCategory.WORKER_SAFETY_EQUIPMENT_PROTOCOLS, label: 'Worker Safety Equipment and Protocols' },
    ],
  },
  {
    name: 'Supplier Ethical Practices',
    key: 'supplier_ethics',
    criteria: [
      { value: EvaluationCriteriaCategory.FAIR_LABOR_PRACTICES_CERTIFICATION, label: 'Fair Labor Practices Certification' },
      { value: EvaluationCriteriaCategory.CONFLICT_OF_INTEREST_DECLARATIONS, label: 'Conflict of Interest Declarations' },
      { value: EvaluationCriteriaCategory.ANTI_BRIBERY_CORRUPTION_POLICIES, label: 'Anti-Bribery and Corruption Policies' },
      { value: EvaluationCriteriaCategory.WHISTLEBLOWER_PROTECTION_MECHANISMS, label: 'Whistleblower Protection Mechanisms' },
      { value: EvaluationCriteriaCategory.CORPORATE_GOVERNANCE_STANDARDS, label: 'Corporate Governance Standards' },
      { value: EvaluationCriteriaCategory.HUMAN_RIGHTS_COMPLIANCE, label: 'Human Rights Compliance' },
      { value: EvaluationCriteriaCategory.TRANSPARENCY_IN_SUPPLY_CHAIN, label: 'Transparency in Supply Chain' },
      { value: EvaluationCriteriaCategory.ETHICAL_SOURCING_VERIFICATION, label: 'Ethical Sourcing Verification' },
      { value: EvaluationCriteriaCategory.SUPPLIER_CODE_OF_CONDUCT, label: 'Supplier Code of Conduct' },
    ],
  },
  {
    name: 'Adaptability & Flexibility',
    key: 'adaptability',
    criteria: [
      { value: EvaluationCriteriaCategory.CHANGE_MANAGEMENT_CAPACITY, label: 'Change Management Capacity' },
      { value: EvaluationCriteriaCategory.SUPPLIER_INNOVATION_CAPACITY, label: 'Supplier Innovation Capacity' },
      { value: EvaluationCriteriaCategory.RESPONSIVENESS_TO_SCOPE_CHANGES, label: 'Responsiveness to Scope Changes' },
      { value: EvaluationCriteriaCategory.ABILITY_TO_MANAGE_TECHNOLOGY_CHANGES, label: 'Ability to Manage Technology Changes' },
      { value: EvaluationCriteriaCategory.FLEXIBILITY_IN_CONTRACT_TERMS, label: 'Flexibility in Contract Terms' },
      { value: EvaluationCriteriaCategory.SCALABILITY_OF_SERVICES_PRODUCTS, label: 'Scalability of Services or Products' },
      { value: EvaluationCriteriaCategory.CUSTOMIZATION_OPTIONS, label: 'Customization Options' },
      { value: EvaluationCriteriaCategory.ABILITY_TO_FAST_TRACK_DELIVERY, label: 'Ability to Fast-track Delivery' },
    ],
  },
  {
    name: 'Contract Management & Performance',
    key: 'contract_management',
    criteria: [
      { value: EvaluationCriteriaCategory.KPI_DEFINITION_MEASUREMENT, label: 'KPI Definition and Measurement' },
      { value: EvaluationCriteriaCategory.CONTRACT_ADMINISTRATION_EXPERIENCE, label: 'Contract Administration Experience' },
      { value: EvaluationCriteriaCategory.REPORTING_COMMUNICATION_PLANS, label: 'Reporting and Communication Plans' },
      { value: EvaluationCriteriaCategory.CONTINUOUS_IMPROVEMENT_PLANS, label: 'Continuous Improvement Plans' },
      { value: EvaluationCriteriaCategory.DISPUTE_RESOLUTION_MECHANISMS, label: 'Dispute Resolution Mechanisms' },
      { value: EvaluationCriteriaCategory.PERFORMANCE_INCENTIVES, label: 'Performance Incentives' },
      { value: EvaluationCriteriaCategory.ISSUE_ESCALATION_PROCEDURES, label: 'Issue Escalation Procedures' },
      { value: EvaluationCriteriaCategory.POST_CONTRACT_SUPPORT, label: 'Post-Contract Support' },
    ],
  },
  {
    name: 'Social & Economic Objectives',
    key: 'social_economic',
    criteria: [
      { value: EvaluationCriteriaCategory.LOCAL_CONTENT_EMPLOYMENT_CREATION, label: 'Local Content and Employment Creation' },
      { value: EvaluationCriteriaCategory.SUPPORT_FOR_SMES, label: 'Support for SMEs' },
      { value: EvaluationCriteriaCategory.EMPOWERMENT_OF_DISADVANTAGED_GROUPS, label: 'Empowerment of Disadvantaged Groups' },
      { value: EvaluationCriteriaCategory.ADVANCEMENT_OF_GENDER_EQUALITY, label: 'Advancement of Gender Equality' },
      { value: EvaluationCriteriaCategory.REGIONAL_ECONOMIC_DEVELOPMENT_IMPACT, label: 'Regional Economic Development Impact' },
      { value: EvaluationCriteriaCategory.CONTRIBUTION_TO_SOCIAL_INFRASTRUCTURE, label: 'Contribution to Social Infrastructure' },
      { value: EvaluationCriteriaCategory.SUPPLIER_DIVERSITY_INITIATIVES, label: 'Supplier Diversity Initiatives' },
      { value: EvaluationCriteriaCategory.COMMUNITY_DEVELOPMENT_PROGRAMS, label: 'Community Development Programs' },
    ],
  },
  {
    name: 'Market & Competitive Dynamics',
    key: 'market_competitive',
    criteria: [
      { value: EvaluationCriteriaCategory.MARKET_POSITION_SHARE, label: 'Market Position and Share' },
      { value: EvaluationCriteriaCategory.COLLABORATIVE_PARTNERSHIP_POTENTIAL, label: 'Collaborative and Partnership Potential' },
      { value: EvaluationCriteriaCategory.CO_INNOVATION_POSSIBILITIES, label: 'Co-Innovation Possibilities' },
      { value: EvaluationCriteriaCategory.SUPPLY_BASE_DIVERSITY, label: 'Supply Base Diversity' },
      { value: EvaluationCriteriaCategory.LONG_TERM_RELATIONSHIP_POTENTIAL, label: 'Long-term Relationship Potential' },
      { value: EvaluationCriteriaCategory.COMPETITIVE_ADVANTAGE_CONTRIBUTIONS, label: 'Competitive Advantage Contributions' },
      { value: EvaluationCriteriaCategory.TECHNOLOGY_LEADERSHIP, label: 'Technology Leadership' },
      { value: EvaluationCriteriaCategory.INDUSTRY_INFLUENCE_LEADERSHIP, label: 'Industry Influence and Leadership' },
    ],
  },
];

export const formatCriteriaLabel = (key: string): string => {
  return key
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};
