// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmchyxkgbgbrxrqfkrqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtY2h5eGtnYmdicnhycWZrcnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTk3NTUsImV4cCI6MjA1NjkzNTc1NX0._EWOiVpPSUy6f7q5tHgXg3MRvWPyulNx-dcT9g4prIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);